apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ghost-deployment
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: ghost
      stage: dev
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: ghost
        stage: dev
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: ghost
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          resources:
            limits:
              memory: "512Mi"
          ports:
            - containerPort: 2368
          env:
            - name: database__client
              value: mysql
            - name: database__connection__host
              value: {{ .Release.Name }}-mysql-service
            - name: database__connection__user
              value: ghost_user
            - name: database__connection__password
              value: ghost_password
            - name: database__connection__database
              value: ghost
            - name: url
              value: http://{{ .Release.Name }}.ghost.localhost

