apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}-wordpress
      stage: {{ .Values.stage }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-wordpress
        stage: {{ .Values.stage }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          env:
          - name: WORDPRESS_DB_HOST
            value: {{ .Release.Name }}-db
          - name: WORDPRESS_DB_USER
            value: exampleuser
          - name: WORDPRESS_DB_PASSWORD
            value: examplepass
          - name: WORDPRESS_DB_NAME
            value: exampledb
          ports:
            - containerPort: 80

            
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-db
spec:
  replicas: 1
  serviceName: {{ .Release.Name }}-db
  selector:
    matchLabels:
      name: {{ .Release.Name }}-db
      stage: {{ .Values.stage }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-db
        stage: {{ .Values.stage }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-db
          image: mysql:5.7
          env:
          - name: MYSQL_DATABASE
            value: exampledb
          - name: MYSQL_USER
            value: exampleuser
          - name: MYSQL_PASSWORD
            value: examplepass
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value: '1'
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /usr/upload/
              name: {{ .Release.Name }}-storage
      volumes:
        - name: {{ .Release.Name }}-storage
          persistentVolumeClaim:
              claimName: {{ .Release.Name }}-claim