apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
spec:
  selector:
    name: {{ .Release.Name }}-db
    stage: {{ .Values.stage }}
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wordpress
spec:
  selector:
    name: {{ .Release.Name }}-wordpress
    stage: {{ .Values.stage }}
    release: {{ .Release.Name }}
  type: LoadBalancer
  ports:
    - port: {{ .Values.ports.public }}
      targetPort: 80
